### ISSUE TITLE
[Alexandria] 502 error when decrypting on sepolia and baseSepolia

### ISSUE THREAD

**Issue by robyn3choi** [LIT-Protocol/Issues-and-Reports#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

5.0.0

### Lit Network

habanero

### Description of the bug/issue

I'm encrypting and decrypting a string using the [Quick Start](https://developer.litprotocol.com/v3/sdk/access-control/quick-start) in the Lit docs, but I get this error when I try to use `sepolia` or `baseSepolia` instead of `ethereum` in the `accessControlConditions`.

![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/9066587/5e5c20f5-8ed8-4bdf-ab80-3a0bf855c61b)

### Severity of the bug

high - it's blocking us from using Lit v3 (we're still using v2)

### Steps To Reproduce

1. Clone the repo at [https://github.com/robyn3choi/lit-issue](https://github.com/robyn3choi/lit-issue)
2. In src/lit.ts, replace capacityTokenId on line 42 with your capacity token's ID.
3. Run yarn to install packages
4. Run yarn dev to run the app locally
5. Click "Encrypt" and wait for the results of the encryption to display.
6. Click "Decrypt". Open the browser console to see the errors.

### Link to code

[https://github.com/robyn3choi/lit-issue](https://github.com/robyn3choi/lit-issue)

**Comment by spacesailor24** [comment]
Thank you for bringing this to our attention, and thank you for the reproduction steps!

I was able to reproduce the 401s and 502s, I will escalate this to our eng team, and get back to you when we have a response

**Comment by robyn3choi** [comment]
thanks, btw I just edited the Steps to Reproduce to remove a step that didn't make sense (it was a copy-paste error from a previous issue I posted here)

**Comment by spacesailor24** [comment]
After investigation from the team, both `sepolia` and `baseSepolia` are not currently supported by the `habanero` network - They will be in the upcoming `v0.1` network update which our team is currently working on getting deployed

**Comment by robyn3choi** [comment]
Ah ok, if I switch `litNetwork` to `cayenne` and remove `checkNodeAttestation`, then it works. Are there other networks listed in the [Supported Blockchains](https://developer.litprotocol.com/v3/resources/supported-chains#supported-chains-access-control--pkp) that don't currently work on `habanero`?

**Comment by spacesailor24** [comment]
@robyn3choi Forwarded your question to our eng team, will let you know what they say

**Comment by spacesailor24** [comment]
@robyn3choi Unfortunately each node in Habanero keeps a list of it's own RPC urls and it's private, so there's not a way to easily tell what networks are broadly supported by the nodes for Habanero

**Comment by spacesailor24** [comment]
@robyn3choi

These are the chains currently support on Habanero and Manzano

```
chains:
  ethereum:
    - url: https://eth.llamarpc.com/
  polygon:
    - url: "https://polygon-rpc.com/"
  mumbai:
    - url: https://matic-mumbai.chainstacklabs.com/
  xdai:
    - url: "https://rpc.gnosischain.com/"
  chiado:
    - url: "https://rpc.chiadochain.net/"
  base:
    - url: https://mainnet.base.org/
  baseGoerli:
    - url: https://goerli.base.org/
  bsc:
    - url: "https://bsc-dataseed.binance.org/"
  fantom:
    - url: "https://rpcapi.fantom.network/"
  arbitrum:
    - url: "https://arb1.arbitrum.io/rpc"
  avalanche:
    - url: "https://api.avax.network/ext/bc/C/rpc"
  harmony:
    - url: "https://rpc.s0.t.hmny.io/"
  goerli:
    - url: https://goerli.infura.io/v3/b6bf7d3508c941499b10025c0776eaf8
  cronos:
    - url: "https://evm-cronos.org/"
  optimism:
    - url: https://mainnet.optimism.io/
  celo:
    - url: "https://forno.celo.org/"
  fuji:
    - url: "https://api.avax-test.network/ext/bc/C/rpc"
  aurora:
    - url: "https://mainnet.aurora.dev/"
  eluvio:
    - url: "https://host-76-74-28-226.contentfabric.io/eth"
  alfajores:
    - url: "https://alfajores-forno.celo-testnet.org/"
  xdc:
    - url: "https://rpc.xinfin.network/"
  evmos:
    - url: "https://eth.bd.evmos.org:8545/"
  evmosTestnet:
    - url: "https://eth.bd.evmos.dev:8545/"
  litTestnet:
    - url: "https://lit.calderachain.xyz/http"
  lit:
    - url: "https://lit-protocol.calderachain.xyz/http"
  lukso:
    - url: https://rpc.lukso.gateway.fm/
  luksoTestnet:
    - url: https://rpc.testnet.lukso.network/
  sepolia:
    - url: https://eth-sepolia.g.alchemy.com/v2/demo
  zkSync:
    - url: "https://mainnet.era.zksync.io/"
  zksyncTestnet:
    - url: "https://testnet.era.zksync.dev/"
  linea:
    - url: https://rpc.goerli.linea.build/
  zkEvm:
    - url: https://zkevm-rpc.com/
  zora:
    - url: https://rpc.zora.energy/
  zoraGoerli:
    - url: https://testnet.rpc.zora.energy/
  mantleTestnet:
    - url: https://rpc.testnet.mantle.xyz/
  mantle:
    - url: https://rpc.mantle.xyz/
  klaytn:
    - url: https://klaytn.blockpi.network/v1/rpc/public
  publicGoodsNetwork:
    - url: https://rpc.publicgoods.network/
```

And the list for Cayenne:

```
chains:
  alfajores:
    - url: https://alfajores-forno.celo-testnet.org/
  anvil:
    - url: http://127.0.0.1:8545/
  arbitrum:
    - url: https://arb1.arbitrum.io/rpc
  aurora:
    - url: https://mainnet.aurora.dev/
  avalanche:
    - url: https://api.avax.network/ext/bc/C/rpc
  base:
    - url: https://mainnet.base.org/
  baseGoerli:
    - url: https://goerli.base.org/
  baseSepolia:
    - url: https://sepolia.base.org/
  bsc:
    - url: https://bsc-dataseed.binance.org/
  celo:
    - url: https://forno.celo.org/
  cheqdMainnet:
    - url: https://api.cheqd.net/
  cheqdTestnet:
    - url: https://api.cheqd.network/
  chiado:
    - url: https://rpc.chiadochain.net/
  chronicleTestnet:
    - url: https://chain-rpc.litprotocol.com/http
  cosmos:
    - url: https://lcd-cosmoshub.keplr.app/
  cronos:
    - url: https://evm-cronos.org/
  eluvio:
    - url: https://host-76-74-28-226.contentfabric.io/eth
  ethereum:
    - url: https://mainnet.infura.io/v3/96dffb3d8c084dec952c61bd6230af34
    - url: https://eth-mainnet.g.alchemy.com/v2/csvV3bBtx2v8uX3APunm8z-HD3Twqa8Q
  evmos:
    - url: https://eth.bd.evmos.org:8545/
  evmosTestnet:
    - url: https://eth.bd.evmos.dev:8545/
  fantom:
    - url: https://rpcapi.fantom.network/
  filecoin:
    - url: https://api.node.glif.io/rpc/v1
  hyperspace:
    - url: https://api.hyperspace.node.glif.io/rpc/v1
  fuji:
    - url: https://api.avax-test.network/ext/bc/C/rpc
  goerli:
    - url: https://goerli.infura.io/v3/96dffb3d8c084dec952c61bd6230af34
  hardhat:
    - url: http://127.0.0.1:8545/
  harmony:
    - url: https://rpc.s0.t.hmny.io/
  juno:
    - url: https://rest.cosmos.directory/juno
  kovan:
    - url: https://kovan.infura.io/v3/96dffb3d8c084dec952c61bd6230af34
  kyve:
    - url: https://api.korellia.kyve.network/
  lineaGoerli:
    - url: https://rpc.goerli.linea.build/
  lit:
    - url: https://lit-protocol.calderachain.xyz/http
  litTestnet:
    - url: "https://lit.calderachain.xyz/http"
  lukso:
    - url: https://rpc.lukso.gateway.fm/
  luksoTestnet:
    - url: https://rpc.testnet.lukso.network/
  moonbaseAlpha:
    - url: https://rpc.api.moonbase.moonbeam.network/
  moonbeam:
    - url: https://rpc.api.moonbeam.network/
  moonriver:
    - url: https://rpc.api.moonriver.moonbeam.network/
  mumbai:
    - url: https://polygon-mumbai.g.alchemy.com/v2/jGDSCo9ynp9AEIA9jdmpp834M1NjwWX-
  optimism:
    - url: https://optimism-mainnet.infura.io/v3/96dffb3d8c084dec952c61bd6230af34
  optimismGoerli:
    - url: https://optimism-goerli.publicnode.com/
  polygon:
    - url: https://polygon-mainnet.g.alchemy.com/v2/D1b4fE8b1DB2YJkkm_lM4_qjqyMdx9Tr
    - url: https://polygon-rpc.com/
  rinkeby:
    - url: https://rinkeby.infura.io/v3/96dffb3d8c084dec952c61bd6230af34
  ropsten:
    - url: https://ropsten.infura.io/v3/96dffb3d8c084dec952c61bd6230af34
  sepolia:
    - url: https://sepolia.infura.io/v3/96dffb3d8c084dec952c61bd6230af34
  scrollAlphaTestnet:
    - url: https://alpha-rpc.scroll.io/l2
  scroll:
    - url: https://rpc.scroll.io/
  solana:
    - url: https://long-wild-fog.solana-mainnet.quiknode.pro/01f8f003ac20c02576f7a205a158a45120102a6d
  solanaDevnet:
    - url: https://solana-devnet.g.alchemy.com/v2/q4EAtK0PRYHz4PavhP8jxaVxwVpSV9de
  solanaTestnet:
    - url: https://api.testnet.solana.com/
  verifyTestnet:
    - url: https://rpc.verify-testnet.gelato.digital/
  xdai:
    - url: https://small-ultra-dawn.xdai.quiknode.pro/5769e900e2fe616d47184f089d98459d6ab2318f
  xdc:
    - url: https://rpc.xinfin.network/
  zkSync:
    - url: https://mainnet.era.zksync.io/
  zksyncTestnet:
    - url: https://testnet.era.zksync.dev/
  zkEvm:
    - url: https://zkevm-rpc.com/
  zora:
    - url: https://rpc.zora.energy/
  zoraGoerli:
    - url: https://testnet.rpc.zora.energy/
  mantleTestnet:
    - url: https://rpc.testnet.mantle.xyz/
  mantle:
    - url: https://rpc.mantle.xyz/
  klaytn:
    - url: https://klaytn.blockpi.network/v1/rpc/public
  publicGoodsNetwork:
    - url: https://rpc.publicgoods.network/
  waevEclipseTestnet:
    - url: https://api.evm.waev.eclipsenetwork.xyz/solana
```
